#!/bin/sh /etc/rc.common
# 路径: package/network-gcxy/files/network-gcxy.init

START=99
USE_PROCD=1

start_service() {
    procd_open_instance
    # 运行脚本
    procd_set_param command /bin/sh /usr/bin/network-gcxy.sh
    # 设定每隔 2 分钟(120秒)自动运行一次脚本进行检测
    # 格式: respawn <临界时间> <重试间隔> <最大重试次数>
    procd_set_param respawn 3600 120 0
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}